### PR TITLE
Use the onbuild python docker images.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Simpler dockerfile!

### CODE REVIEW

**Comment by alex** [comment]
How do the image sizes compare?

**Comment by glogiotatidis** [comment]
[Imagelayers](https://imagelayers.io/?images=alexgaynor%2Fletsencrypt-aws:latest,giorgos%2Fletsencrypt-aws:latest) doesn't work nicely for me today and I can't get the size.

**Comment by glogiotatidis** [comment]
225MB (current) vs 280MB (this one)

It's slightly bigger because it's based on the full python image instead of the slim one. There's no slim image with `onbuild` commands. 

I still I like basing stuff on 'on-build' images, as it results to smaller and cleaner dockerfiles which take full advantage of upstream updates. You call, feel free to go either way. Thanks!

**Comment by alex** [comment]
I feel like this image is already way too big for what it does, so I really don't want to make it larger still. Thanks for sending this though!

**Pull request closed without merging**
