### PR TITLE
Perm `iam:UpdateServerCertificate` is needed

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by alex** [comment]
When is this used?

**Comment by glogiotatidis** [comment]
I tried updating a cert using this client and I got an error that I don't have perms.

**Comment by alex** [comment]
Do you have a traceback showing which operation failed with that error?

**Comment by glogiotatidis** [comment]
Tried to reproduce and it's now working. Maybe an AWS snafu? feel free to close this one.

**Comment by alex** [comment]
Ok! If anyone else reports this issue I'll keep it in mind.

**Pull request closed without merging**
