### PR TITLE
Fixes #18: Truncate ServerCertificateName to 128 characters

### LINKED ISSUE #18: Invalid length for parameter ServerCertificateName, value: 144, valid range: 1-128
Hi,

If you try to generate a certificate with a larger number of domains so 6 or more, because of how the certificate is named (concatenating the domain names) it exceeds the valid length of the ServerCertificateName parameter.

### PR DESCRIPTION
**Pull request by stephenmuss**
letsencrypt-aws fails when `generate_certificate_name` returns a string longer than 128 characters.

ServerCertificateName has a limit of 128 characters. This PR proposes truncated the result from `generate_certificate_name` to 128 characters in the case that it exceeds that length.

Ideally, `generate_certificate_name` should create a name shorter or equal to 128 characters. But truncating ensures that things still work when 128 characters are exceeded.

### CODE REVIEW

**Comment by alex** [comment]
I think I'd prefer the name to always include the full serial and expiration date, can you make it so the host portion is what gets truncated?

**Comment by stephenmuss** [comment]
I did this as a quick fix just to make sure it works when the name exceeds the 128 characters.

I agree that it would be better to include the full serial and expiration date.

I can update it to do that once I've got some extra time to spare.

**Comment by alex** [comment]
Ok, if you don't mind I'll probably just take the patch and run with it then. Thansk!

**Comment by stephenmuss** [comment]
By all means do what you will with it.

**Pull request closed without merging**
